##spring.application.name=test1
##spring.data.mongodb.port = 27017
#spring:
#  data:
#    mongodb:
#  uri : mongodb+srv://sahibpreetsingh432_db_user:GmFdqCfD5QO67hdi@cluster0.1vlrnn2.mongodb.net/?appName=Cluster0
#  database :  journaldb
#  auto-index-creation : true
#
#server:
#  port: 8081
#  servlet:
#  context-path: /journal
##GmFdqCfD5QO67hdi