#spring.application.name=test1
#spring.data.mongodb.port = 27017
spring.data.mongodb.uri=mongodb+srv://sahibpreetsingh432_db_user:GmFdqCfD5QO67hdi@cluster0.1vlrnn2.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = journaldb
spring.data.mognodb.auto-index-creation = true


#GmFdqCfD5QO67hdi



#// it gives priority while using both yml and properties
